### ISSUE TITLE
add a --classic command line parameter

### ISSUE THREAD

**Issue by ericoporto** [rofl0r/ascc#1]
The idea is to have `--classic` to disable features not on mainline ags.

**Comment by rofl0r** [comment]
could you remind me which features those are ?

**Comment by ericoporto** [comment]
I think only *int and *float pointers, but am not sure if there are more changes.

**Comment by rofl0r** [comment]
well, if you don't use those then the compiler will behave exactly as original. the only difference is if you do use them you won't get a compile error but a bytecode that works as expected.

**Comment by ericoporto** [comment]
Ok, it's alright then. I thought there were more changes.
